# Path to your oh-my-zsh configuration.
ZSH=$HOME/.dotfiles/oh-my-zsh

# Set name of the theme to load.
# Look in oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
ZSH_THEME="af-magic"
# ZSH_THEME="agnoster"

# Example aliases
# alias zshconfig="subl ~/.dotfiles/zsh/zshrc"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git virtualenv)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

alias g='git' \
      'g cm'='git commit' \
      psg='ps aux | grep' \
      be='bundle exec' \
      bi='bundle install' \
      dotfiles='subl ~/.dotfiles' \
      nrw='npm run-script watch' \
      gd='grunt dev' \
      gdf='grunt dev --force' \
      gw='grunt watch' \
      notes='subl ~/notes' \
      sup='bundle exec stage-up' \
      bed='bundle exec deploy' \
      iatt='npm install && pac install && npm rebuild && bundle' \
      sl='sl' \
      wow='git status' \
      such='git' \
      very='git' \
      reload='source ~/.zshrc' \
      cdir='echo -n $(pwd) | pbcopy'

# Quick 'mark' filesystem navigation, taken from @jeroenjanssens
# TODO: Add tab completion to this!
export MARKPATH=$HOME/.marks
function j {
    cd -P $MARKPATH/$1 2>/dev/null || echo "No such mark: $1"
}
function mark {
    mkdir -p $MARKPATH; ln -s $(pwd) $MARKPATH/$1
}
function unmark {
    rm -i $MARKPATH/$1
}
function marks {
    ls -l $MARKPATH | sed 's/  / /g' | cut -d' ' -f9- | sed 's/ -/\ -/g' && echo
}

# Doesn't work
# function title {
#     echo -ne "\033]0;"$*"\007"
# }

export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/:$DYLD_LIBRARY_PATH
export PATH=/usr/local/bin:/usr/local/mysql/bin:$PATH
export EDITOR='vim'

# For npm bins
export PATH=$PATH:/usr/local/share/npm/bin

# Increase limit on number of files to watch because OS X's default is way too low
ulimit -n 2048

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

### Added by the Heroku Toolbelt
export PATH="$PATH:/usr/local/heroku/bin"

### Configuration files for Postgres (-D option)
export PGDATA="/usr/local/var/postgres"

# Base16 Shell
BASE16_SCHEME="default"
BASE16_SHELL="$HOME/.dotfiles/base16-shell/base16-$BASE16_SCHEME.dark.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL

