# Path to your oh-my-zsh configuration.
ZSH=$HOME/.dotfiles/oh-my-zsh

# Set name of the theme to load.
# Look in oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
ZSH_THEME="af-magic"
# ZSH_THEME="agnoster"

# Example aliases
# alias zshconfig="subl ~/.dotfiles/zsh/zshrc"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git virtualenv)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

source $HOME/.dotfiles/zsh/aliases

export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/:$DYLD_LIBRARY_PATH
export PATH=/usr/local/bin:~/bin:/usr/local/mysql/bin:$PATH
export EDITOR='vim'

# For npm bins
export PATH=$PATH:/usr/local/share/npm/bin

# Increase limit on number of files to watch because OS X's default is way too low
ulimit -n 2048

### Added by the Heroku Toolbelt
export PATH="$PATH:/usr/local/heroku/bin"

### Configuration files for Postgres (-D option)
export PGDATA="/usr/local/var/postgres"

### OSX STUPIDITY
export ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future

# Base16 Shell
BASE16_SCHEME="default"
BASE16_SHELL="$HOME/.dotfiles/base16-shell/base16-$BASE16_SCHEME.dark.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL

export PATH="$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting

source ~/.private-zshrc
